// frontend/src/app/shared/layout/screen-shell.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { BackHeader } from './back-header.component';

@Component({
  selector: 'app-screen-shell',
  standalone: true,
  imports: [BackHeader],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 sm:py-10">
      @if (back()) {
        <app-back-header [title]="null" [fallback]="backFallback()" />
      }
      <header class="mb-8">
        @if (eyebrow()) {
          <p
            class="mb-3 font-headline text-xs font-bold uppercase tracking-[0.3em] text-primary"
          >
            {{ eyebrow() }}
          </p>
        }
        <h1
          class="font-headline text-3xl font-extrabold leading-tight tracking-tight text-on-surface sm:text-4xl"
        >
          {{ title() }}
        </h1>
        @if (subtitle()) {
          <p class="mt-3 max-w-2xl text-base leading-relaxed text-on-surface-variant">
            {{ subtitle() }}
          </p>
        }
      </header>
      <div>
        <ng-content />
      </div>
    </section>
  `,
})
export class ScreenShell {
  readonly eyebrow = input<string | null>(null);
  readonly title = input.required<string>();
  readonly subtitle = input<string | null>(null);
  readonly back = input<boolean>(false);
  readonly backFallback = input<string | null>(null);
}

// mobile/src/ui/ScreenShell.tsx
import { ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { ReactNode } from 'react';

import { BackHeader } from './BackHeader';

type Props = {
  eyebrow: string;
  title: string;
  subtitle?: string;
  back?: boolean;
  backFallback?: string;
  children: ReactNode;
};

export function ScreenShell({
  eyebrow,
  title,
  subtitle,
  back = false,
  backFallback,
  children,
}: Props) {
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#0b0b0c' }} edges={['top']}>
      {back ? <BackHeader fallbackHref={backFallback} /> : null}
      <ScrollView
        style={{ backgroundColor: '#0b0b0c' }}
        contentContainerStyle={{ paddingBottom: 40, backgroundColor: '#0b0b0c' }}
      >
        <View className="px-4 py-6">
          <Text className="mb-3 font-headline text-xs font-bold uppercase tracking-[3px] text-primary">
            {eyebrow}
          </Text>
          <Text className="font-headline text-3xl font-extrabold leading-tight tracking-tight text-on-surface">
            {title}
          </Text>
          {subtitle ? (
            <Text className="mt-3 text-base leading-relaxed text-on-surface-variant">
              {subtitle}
            </Text>
          ) : null}
          <View className="mt-8">{children}</View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
